### ISSUE TITLE
Registration Page Error

### ISSUE THREAD

**Issue by Jordan-Loeser** [communicode-source/communicode#2]
The registration page is having an error. 

A NOTE ON BRANCHES: Trevor is going to fix the registration branch and merge it to the master branch. AFTER THIS POINT we all have our own branch, so we will maintain the master branch as a version of Communicode that is COMPLETELY STABLE so we can always revert back to a recent safe version should an error occur.

**Comment by jmamaril25** [comment]
I don't know how to do that.
